#!/bin/bash
#
# soacheckd - report changes in serial numbers
#

P=$(basename $0)
BD=$(dirname $0)
DD=${BD}/data
IF="${BD}/zones-to-check"
LOG="${BD}/soacheckd.log"

mkdir -p ${DD}

getSOA() {
	host -t soa $1 > ${DD}/soa.$1
}

SOAvalue() {
	cat ${DD}/soa.$1 | awk '{print $7}'
}

for z in `egrep -v "^(#|$)" ${IF}` ; do
	if [ -r ${DD}/soa.${z} ] ; then
		PREV=$(SOAvalue ${z})
	else
		getSOA ${z}
		PREV=$(SOAvalue ${z})
	fi

	getSOA ${z}
	CURRENT=$(SOAvalue ${z})

	if [ "x${PREV}" != "x${CURRENT}" ] ; then
		echo $(date) ${HOST} ${P}[$$] ${z} serial changed from ${PREV} to ${CURRENT} | tee -a ${LOG}
	fi
done

